### ISSUE TITLE
Use the version from `#testing-releases`.

### ISSUE THREAD

**Issue by Czekista** [Michal78900/MapEditorReborn#14]
Use the version from `#testing-releases`.

_Originally posted by @Michal78900 in https://github.com/Michal78900/MapEditorReborn/issues/10#issuecomment-1023001236_
You're talking about exiled testing release or testing relase of this plugin?

**Comment by Michal78900** [comment]
Of this plugin

**Comment by Czekista** [comment]
From where can I take one? 
Cuz I'm dumb
