### ISSUE TITLE
MapEditor Console Issue

### ISSUE THREAD

**Issue by NewCoderPersonBoi** [Michal78900/MapEditorReborn#8]
So, I've installed the plugin (the dll in plugins folder if that's correct) but before that I made sure to follow the steps to making a custom model (mainly just testing with an example one first) anyways yeah, I followed the steps to make the model then where to put it which would be /EXILED/Configs/MapEditorReborn/Schematics.

Then when I start up the console to make sure it works there's an error that comes up. I go in game to do the command (the mp one) it says command not found. For some reason unless I'm missing something I am having lots of trouble with this.

I'll also leave the issue in the console here also
[maperror.txt](https://github.com/Michal78900/MapEditorReborn/files/7786747/maperror.txt)
.

**Comment by NewCoderPersonBoi** [comment]
Nvm. I thought I found a fix but I guess not

**Comment by Michal78900** [comment]
Not a bug, officially plugin is not updated. You can use the version in #testing-releases or ask me for dll.
